#ifndef DASHBOARD_H
#define DASHBOARD_H

static const char dashboard_html[] =
"<!DOCTYPE html>"
"<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32-P4 micro-ROS</title><style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,-apple-system,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:16px}"
"h1{text-align:center;color:#00d4ff;font-size:1.3em;margin-bottom:12px}"
".g{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}"
".c{background:#16213e;border-radius:8px;padding:14px;border:1px solid #0f3460}"
".c h2{font-size:.95em;color:#00d4ff;margin-bottom:8px;border-bottom:1px solid #0f3460;padding-bottom:6px}"
".r{display:flex;justify-content:space-between;padding:3px 0;font-size:.85em}"
".r .l{color:#8899aa}"
".r .v{color:#e0e0e0;font-family:monospace}"
".bar{background:#0f3460;border-radius:3px;height:14px;margin:4px 0 2px}"
".bar div{background:linear-gradient(90deg,#00d4ff,#0a84ff);height:100%;border-radius:3px;transition:width .5s}"
".bar.psram div{background:linear-gradient(90deg,#a855f7,#7c3aed)}"
"table{width:100%;border-collapse:collapse;font-size:.78em;margin-top:6px}"
"th{text-align:left;color:#00d4ff;border-bottom:1px solid #0f3460;padding:4px 6px}"
"td{padding:3px 6px;border-bottom:1px solid #0a1a30;font-family:monospace}"
".tc{max-height:200px;overflow-y:auto}"
".err{color:#ff6b6b;text-align:center;padding:8px;font-size:.85em}"
"#ts{text-align:center;font-size:.75em;color:#556;margin-top:8px}"
"</style></head><body>"
"<h1>ESP32-P4 micro-ROS Dashboard</h1>"
"<div class='g'>"
  "<div class='c'><h2>System</h2>"
    "<div class='r'><span class='l'>Chip</span><span class='v' id='chip'>--</span></div>"
    "<div class='r'><span class='l'>CPU</span><span class='v' id='cpu'>--</span></div>"
    "<div class='r'><span class='l'>Temperature</span><span class='v' id='tmp'>--</span></div>"
    "<div class='r'><span class='l'>Flash</span><span class='v' id='flash'>--</span></div>"
    "<div class='r'><span class='l'>Reset Reason</span><span class='v' id='rst'>--</span></div>"
    "<div class='r'><span class='l'>Uptime</span><span class='v' id='up'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Memory</h2>"
    "<div class='r'><span class='l'>Internal SRAM</span><span class='v' id='imem'>--</span></div>"
    "<div class='bar'><div id='ib' style='width:0%'></div></div>"
    "<div class='r'><span class='l'>PSRAM</span><span class='v' id='pmem'>--</span></div>"
    "<div class='bar psram'><div id='pb' style='width:0%'></div></div>"
    "<div class='r'><span class='l'>Heap Watermark</span><span class='v' id='hwm'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Ethernet</h2>"
    "<div class='r'><span class='l'>Link</span><span class='v' id='lnk'>--</span></div>"
    "<div class='r'><span class='l'>Speed</span><span class='v' id='spd'>--</span></div>"
    "<div class='r'><span class='l'>PHY</span><span class='v' id='phy'>--</span></div>"
    "<div class='r'><span class='l'>MAC</span><span class='v' id='mac'>--</span></div>"
    "<div class='r'><span class='l'>IP</span><span class='v' id='ip'>--</span></div>"
    "<div class='r'><span class='l'>Gateway</span><span class='v' id='gw'>--</span></div>"
    "<div class='r'><span class='l'>Netmask</span><span class='v' id='nm'>--</span></div>"
  "</div>"
  "<div class='c'><h2>micro-ROS</h2>"
    "<div class='r'><span class='l'>Publishes</span><span class='v' id='pub'>--</span></div>"
    "<div class='r'><span class='l'>Servo 0</span><span class='v' id='s0'>--</span></div>"
    "<div class='r'><span class='l'>Servo 1</span><span class='v' id='s1'>--</span></div>"
    "<div class='r'><span class='l'>Servo 2</span><span class='v' id='s2'>--</span></div>"
    "<div class='r'><span class='l'>Servo 3</span><span class='v' id='s3'>--</span></div>"
  "</div>"
  "<div class='c' style='grid-column:1/-1'><h2>FreeRTOS Tasks</h2>"
    "<div class='r'><span class='l'>Total</span><span class='v' id='tc'>--</span></div>"
    "<div class='r'><span class='l'>Core 0 / Core 1</span><span class='v' id='cc'>--</span></div>"
    "<div class='tc'><table><thead><tr><th>Name</th><th>Core</th><th>Priority</th><th>Stack HWM</th></tr></thead>"
    "<tbody id='tt'></tbody></table></div>"
  "</div>"
"</div>"
"<div id='ts'></div>"
"<div class='err' id='err'></div>"
"<script>"
"var E=document.getElementById.bind(document);"
"function fmt(s){var d=Math.floor(s/86400),h=Math.floor(s%86400/3600),"
"m=Math.floor(s%3600/60),ss=s%60;"
"return(d?d+'d ':'')+(h<10?'0':'')+h+':'+(m<10?'0':'')+m+':'+(ss<10?'0':'')+ss}"
"function kb(b){return(b/1024).toFixed(1)+' KB'}"
"function mb(b){return(b/1048576).toFixed(1)+' MB'}"
"function pct(f,t){return t>0?Math.round(((t-f)/t)*100):0}"
"function poll(){"
"fetch('/api/stats').then(function(r){return r.json()}).then(function(d){"
"E('err').textContent='';"
"E('chip').textContent=d.chip_model+' rev '+d.chip_rev;"
"E('cpu').textContent=d.cpu_freq_mhz+' MHz (dual-core RISC-V)';"
"E('tmp').textContent=d.temperature.toFixed(1)+' \\u00B0C';"
"E('flash').textContent=mb(d.flash_size);"
"E('rst').textContent=d.reset_reason;"
"E('up').textContent=fmt(d.uptime_s);"
"var iu=d.internal_total-d.internal_free,ip=pct(d.internal_free,d.internal_total);"
"E('imem').textContent=kb(iu)+' / '+kb(d.internal_total)+' ('+ip+'%)';"
"E('ib').style.width=ip+'%';"
"var pu=d.psram_total-d.psram_free,pp=pct(d.psram_free,d.psram_total);"
"E('pmem').textContent=mb(pu)+' / '+mb(d.psram_total)+' ('+pp+'%)';"
"E('pb').style.width=pp+'%';"
"E('hwm').textContent=kb(d.heap_min_free)+' (min-ever-free)';"
"E('lnk').textContent=d.eth_link?'UP':'DOWN';"
"E('lnk').style.color=d.eth_link?'#4a6':'#f66';"
"E('spd').textContent=d.eth_speed+' Mbps '+(d.eth_duplex?'Full':'Half')+'-duplex';"
"E('phy').textContent=d.eth_phy;"
"E('mac').textContent=d.eth_mac;"
"E('ip').textContent=d.eth_ip;"
"E('gw').textContent=d.eth_gw;"
"E('nm').textContent=d.eth_netmask;"
"E('pub').textContent=d.pub_count;"
"for(var i=0;i<4;i++)E('s'+i).textContent=d.servos[i].toFixed(1)+'\\u00B0';"
"E('tc').textContent=d.task_count;"
"E('cc').textContent=d.core0_tasks+' / '+d.core1_tasks;"
"var h='';for(var i=0;i<d.tasks.length;i++){var t=d.tasks[i];"
"h+='<tr><td>'+t.name+'</td><td>'+(t.core<0?'Any':t.core)+'</td><td>'+t.pri+'</td><td>'+t.hwm+' B</td></tr>'}"
"E('tt').innerHTML=h;"
"E('ts').textContent='Updated: '+new Date().toLocaleTimeString();"
"}).catch(function(e){E('err').textContent='Connection lost'})}"
"poll();setInterval(poll,2000);"
"</script></body></html>";

#endif // DASHBOARD_H
