#ifndef DASHBOARD_H
#define DASHBOARD_H

static const char dashboard_html[] =
"<!DOCTYPE html>"
"<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32-P4 micro-ROS</title><style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,-apple-system,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:16px}"
"h1{text-align:center;color:#00d4ff;font-size:1.3em;margin-bottom:12px}"
".g{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}"
".c{background:#16213e;border-radius:8px;padding:14px;border:1px solid #0f3460}"
".c h2{font-size:.95em;color:#00d4ff;margin-bottom:8px;border-bottom:1px solid #0f3460;padding-bottom:6px}"
".r{display:flex;justify-content:space-between;padding:3px 0;font-size:.85em}"
".r .l{color:#8899aa}"
".r .v{color:#e0e0e0;font-family:monospace}"
".bar{background:#0f3460;border-radius:3px;height:14px;margin:4px 0 2px}"
".bar div{background:linear-gradient(90deg,#00d4ff,#0a84ff);height:100%;border-radius:3px;transition:width .5s}"
".bar.psram div{background:linear-gradient(90deg,#a855f7,#7c3aed)}"
"table{width:100%;border-collapse:collapse;font-size:.78em;margin-top:6px}"
"th{text-align:left;color:#00d4ff;border-bottom:1px solid #0f3460;padding:4px 6px}"
"td{padding:3px 6px;border-bottom:1px solid #0a1a30;font-family:monospace}"
".tc{max-height:200px;overflow-y:auto}"
".err{color:#ff6b6b;text-align:center;padding:8px;font-size:.85em}"
".btn{background:#0f3460;color:#00d4ff;border:1px solid #00d4ff;border-radius:4px;padding:6px 12px;cursor:pointer;font-size:.8em;flex:1}"
".btn:hover{background:#1a4a80}"
".btn:disabled{opacity:.4;cursor:not-allowed}"
"#ts{text-align:center;font-size:.75em;color:#556;margin-top:8px}"
"</style></head><body>"
"<h1>ESP32-P4 micro-ROS Dashboard</h1>"
"<div class='g'>"
  "<div class='c'><h2>System</h2>"
    "<div class='r'><span class='l'>Chip</span><span class='v' id='chip'>--</span></div>"
    "<div class='r'><span class='l'>CPU</span><span class='v' id='cpu'>--</span></div>"
    "<div class='r'><span class='l'>Temperature</span><span class='v' id='tmp'>--</span></div>"
    "<div class='r'><span class='l'>Flash</span><span class='v' id='flash'>--</span></div>"
    "<div class='r'><span class='l'>Reset Reason</span><span class='v' id='rst'>--</span></div>"
    "<div class='r'><span class='l'>Uptime</span><span class='v' id='up'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Memory</h2>"
    "<div class='r'><span class='l'>Internal SRAM</span><span class='v' id='imem'>--</span></div>"
    "<div class='bar'><div id='ib' style='width:0%'></div></div>"
    "<div class='r'><span class='l'>PSRAM</span><span class='v' id='pmem'>--</span></div>"
    "<div class='bar psram'><div id='pb' style='width:0%'></div></div>"
    "<div class='r'><span class='l'>Heap Watermark</span><span class='v' id='hwm'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Ethernet</h2>"
    "<div class='r'><span class='l'>Link</span><span class='v' id='lnk'>--</span></div>"
    "<div class='r'><span class='l'>Speed</span><span class='v' id='spd'>--</span></div>"
    "<div class='r'><span class='l'>PHY</span><span class='v' id='phy'>--</span></div>"
    "<div class='r'><span class='l'>MAC</span><span class='v' id='mac'>--</span></div>"
    "<div class='r'><span class='l'>IP</span><span class='v' id='ip'>--</span></div>"
    "<div class='r'><span class='l'>Gateway</span><span class='v' id='gw'>--</span></div>"
    "<div class='r'><span class='l'>Netmask</span><span class='v' id='nm'>--</span></div>"
  "</div>"
  "<div class='c'><h2>WiFi</h2>"
    "<div style='display:flex;gap:6px;margin-bottom:8px'>"
      "<button class='btn' id='wbtn' onclick='wifiToggle()'>Connect</button>"
    "</div>"
    "<div class='r'><span class='l'>Status</span><span class='v' id='wst'>--</span></div>"
    "<div class='r'><span class='l'>SSID</span><span class='v' id='wssid'>--</span></div>"
    "<div class='r'><span class='l'>RSSI</span><span class='v' id='wrssi'>--</span></div>"
    "<div class='r'><span class='l'>Channel</span><span class='v' id='wch'>--</span></div>"
    "<div class='r'><span class='l'>Auth</span><span class='v' id='wauth'>--</span></div>"
    "<div class='r'><span class='l'>MAC</span><span class='v' id='wmac'>--</span></div>"
    "<div class='r'><span class='l'>IP</span><span class='v' id='wip'>--</span></div>"
    "<div class='r'><span class='l'>Gateway</span><span class='v' id='wgw'>--</span></div>"
    "<div class='r'><span class='l'>Netmask</span><span class='v' id='wnm'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Servos</h2>"
    "<div class='r'><span class='l'>Ch 0</span><span class='v'>"
      "<input type='range' min='0' max='180' value='90' id='sv0' "
        "style='width:140px;accent-color:#00d4ff' oninput='setServo(0,this.value)'>"
      "<span id='s0' style='min-width:40px;text-align:right'>90&deg;</span></span></div>"
    "<div class='r'><span class='l'>Ch 1</span><span class='v'>"
      "<input type='range' min='0' max='180' value='90' id='sv1' "
        "style='width:140px;accent-color:#00d4ff' oninput='setServo(1,this.value)'>"
      "<span id='s1' style='min-width:40px;text-align:right'>90&deg;</span></span></div>"
    "<div class='r'><span class='l'>Ch 2</span><span class='v'>"
      "<input type='range' min='0' max='180' value='90' id='sv2' "
        "style='width:140px;accent-color:#00d4ff' oninput='setServo(2,this.value)'>"
      "<span id='s2' style='min-width:40px;text-align:right'>90&deg;</span></span></div>"
    "<div class='r'><span class='l'>Ch 3</span><span class='v'>"
      "<input type='range' min='0' max='180' value='90' id='sv3' "
        "style='width:140px;accent-color:#00d4ff' oninput='setServo(3,this.value)'>"
      "<span id='s3' style='min-width:40px;text-align:right'>90&deg;</span></span></div>"
    "<div style='display:flex;gap:6px;margin-top:8px'>"
      "<button class='btn' onclick='centreServos()'>Centre All</button>"
    "</div>"
    "<div class='r' style='margin-top:6px'><span class='l'>micro-ROS Publishes</span><span class='v' id='pub'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Audio</h2>"
    "<div style='display:flex;gap:6px;margin-bottom:8px;align-items:center'>"
      "<span class='l' style='font-size:.8em;white-space:nowrap'>Vol</span>"
      "<input type='range' min='0' max='100' value='70' id='rvol' "
        "style='flex:1;accent-color:#00d4ff' oninput='radioVol(this.value)'>"
      "<span class='v' id='rvlbl' style='min-width:32px;text-align:right'>70%</span>"
    "</div>"
    "<div style='display:flex;gap:6px;margin-bottom:8px;align-items:center'>"
      "<button class='btn' onclick='radioCmd(\"prev\")' style='flex:none;padding:8px 10px;font-size:.9em'>&#9664;</button>"
      "<button class='btn' id='rbtn' onclick='radioToggle()' style='flex:none;padding:8px 16px;font-size:.9em'>Play</button>"
      "<button class='btn' id='rpause' onclick='radioCmd(\"pause\")' style='flex:none;padding:8px 10px;font-size:.9em'>&#9646;&#9646;</button>"
      "<button class='btn' onclick='radioCmd(\"next\")' style='flex:none;padding:8px 10px;font-size:.9em'>&#9654;</button>"
      "<select id='rsrc' onchange='radioSrc(this.value)' style='background:#0f3460;color:#e0e0e0;border:1px solid #00d4ff;border-radius:4px;padding:5px 8px;font-size:.8em'>"
        "<option value='sdcard'>SD Card</option>"
        "<option value='stream'>SLAY Radio</option>"
      "</select>"
    "</div>"
    "<div class='r'><span class='l'>Source</span><span class='v' id='rsrclbl'>SD Card</span></div>"
    "<div class='r'><span class='l'>Status</span><span class='v' id='rstat'>Stopped</span></div>"
    "<div class='r'><span class='l'>Now Playing</span><span class='v' id='rtitle' style='max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap'>--</span></div>"
  "</div>"
  "<div class='c'><h2>Ultrasonic</h2>"
    "<div class='r'><span class='l'>Distance</span><span class='v' id='udist'>--</span></div>"
    "<div class='bar'><div id='ub' style='width:0%;background:linear-gradient(90deg,#00d4ff,#00ff88);transition:width .3s'></div></div>"
    "<div class='r'><span class='l'>Raw (mm)</span><span class='v' id='umm'>--</span></div>"
  "</div>"
  "<div class='c'><h2>OLED Display</h2>"
    "<div style='margin-bottom:6px'>"
      "<textarea id='oledtxt' rows='4' style='width:100%;background:#0a1a30;color:#e0e0e0;border:1px solid #0f3460;border-radius:4px;padding:6px;font-family:monospace;font-size:.8em;resize:vertical'"
        " placeholder='Line 1&#10;Line 2&#10;Line 3&#10;...'></textarea>"
    "</div>"
    "<div style='display:flex;gap:6px;margin-bottom:8px;align-items:center'>"
      "<button class='btn' onclick='oledSend()'>Send Text</button>"
      "<button class='btn' onclick='oledSend(1)'>Send Large</button>"
      "<button class='btn' onclick='oledCmd(\"clear\")'>Clear</button>"
      "<button class='btn' id='olddist' onclick='oledLive()'>Live Distance</button>"
      "<button class='btn' id='oldvu' onclick='oledVu()'>VU Meter</button>"
    "</div>"
    "<div style='display:flex;gap:6px;align-items:center'>"
      "<button class='btn' id='oldinv' onclick='oledInvert()'>Invert</button>"
      "<button class='btn' onclick='oledCmd(\"off\")'>Off</button>"
      "<button class='btn' onclick='oledCmd(\"on\")'>On</button>"
      "<span class='l' style='font-size:.8em;margin-left:6px'>Contrast</span>"
      "<input type='range' min='0' max='255' value='207' id='oldcon' "
        "style='width:80px;accent-color:#00d4ff' oninput='oledContrast(this.value)'>"
    "</div>"
  "</div>"
  "<div class='c'><h2>RGB LEDs</h2>"
    "<div style='display:flex;gap:6px;margin-bottom:8px'>"
      "<button class='btn' id='lshow' onclick='ledCmd(\"lightshow\")'>Light Show</button>"
      "<button class='btn' id='lvu' onclick='ledCmd(\"vu\")'>VU Meter</button>"
      "<button class='btn' onclick='ledCmd(\"off\")'>Off</button>"
    "</div>"
  "</div>"
  "<div class='c'><h2>Network Test</h2>"
    "<div style='margin-bottom:6px;font-size:.8em;color:#8899aa'>Ethernet (via current connection)</div>"
    "<div style='display:flex;gap:6px;margin-bottom:8px'>"
      "<button class='btn' onclick='bwTest(\"zero\")'>Zero-Fill</button>"
      "<button class='btn' onclick='bwTest(\"random\")'>Random</button>"
      "<button class='btn' onclick='bwTest(\"pattern\")'>Pattern</button>"
    "</div>"
    "<div class='bar'><div id='bwb' style='width:0%;transition:width .3s'></div></div>"
    "<div class='r'><span class='l'>Status</span><span class='v' id='bws'>Ready</span></div>"
    "<div class='r'><span class='l'>Throughput</span><span class='v' id='bwt'>--</span></div>"
    "<div class='r'><span class='l'>Time</span><span class='v' id='bwd'>--</span></div>"
    "<div class='r'><span class='l'>Data</span><span class='v' id='bwz'>--</span></div>"
    "<div style='margin-top:10px;margin-bottom:6px;font-size:.8em;color:#8899aa'>WiFi (via WiFi IP)</div>"
    "<div style='display:flex;gap:6px;margin-bottom:8px'>"
      "<button class='btn' onclick='bwTestWifi(\"zero\")'>Zero-Fill</button>"
      "<button class='btn' onclick='bwTestWifi(\"random\")'>Random</button>"
      "<button class='btn' onclick='bwTestWifi(\"pattern\")'>Pattern</button>"
    "</div>"
    "<div class='bar'><div id='wbwb' style='width:0%;transition:width .3s'></div></div>"
    "<div class='r'><span class='l'>Status</span><span class='v' id='wbws'>Ready</span></div>"
    "<div class='r'><span class='l'>Throughput</span><span class='v' id='wbwt'>--</span></div>"
    "<div class='r'><span class='l'>Time</span><span class='v' id='wbwd'>--</span></div>"
    "<div class='r'><span class='l'>Data</span><span class='v' id='wbwz'>--</span></div>"
  "</div>"
  "<div class='c' style='grid-column:1/-1'><h2>FreeRTOS Tasks</h2>"
    "<div class='r'><span class='l'>Total</span><span class='v' id='tc'>--</span></div>"
    "<div class='r'><span class='l'>Core 0 / Core 1</span><span class='v' id='cc'>--</span></div>"
    "<div class='tc'><table><thead><tr><th>Name</th><th>Core</th><th>Priority</th><th>Stack HWM</th></tr></thead>"
    "<tbody id='tt'></tbody></table></div>"
  "</div>"
"</div>"
"<div id='ts'></div>"
"<div class='err' id='err'></div>"
"<script>"
"var E=document.getElementById.bind(document);"
"function fmt(s){var d=Math.floor(s/86400),h=Math.floor(s%86400/3600),"
"m=Math.floor(s%3600/60),ss=s%60;"
"return(d?d+'d ':'')+(h<10?'0':'')+h+':'+(m<10?'0':'')+m+':'+(ss<10?'0':'')+ss}"
"function kb(b){return(b/1024).toFixed(1)+' KB'}"
"function mb(b){return(b/1048576).toFixed(1)+' MB'}"
"function pct(f,t){return t>0?Math.round(((t-f)/t)*100):0}"
"function poll(){"
"fetch('/api/stats').then(function(r){return r.json()}).then(function(d){"
"E('err').textContent='';"
"E('chip').textContent=d.chip_model+' rev '+d.chip_rev;"
"E('cpu').textContent=d.cpu_freq_mhz+' MHz (dual-core RISC-V)';"
"E('tmp').textContent=d.temperature.toFixed(1)+' \\u00B0C';"
"E('flash').textContent=mb(d.flash_size);"
"E('rst').textContent=d.reset_reason;"
"E('up').textContent=fmt(d.uptime_s);"
"var iu=d.internal_total-d.internal_free,ip=pct(d.internal_free,d.internal_total);"
"E('imem').textContent=kb(iu)+' / '+kb(d.internal_total)+' ('+ip+'%)';"
"E('ib').style.width=ip+'%';"
"var pu=d.psram_total-d.psram_free,pp=pct(d.psram_free,d.psram_total);"
"E('pmem').textContent=mb(pu)+' / '+mb(d.psram_total)+' ('+pp+'%)';"
"E('pb').style.width=pp+'%';"
"E('hwm').textContent=kb(d.heap_min_free)+' (min-ever-free)';"
"E('lnk').textContent=d.eth_link?'UP':'DOWN';"
"E('lnk').style.color=d.eth_link?'#4a6':'#f66';"
"E('spd').textContent=d.eth_speed+' Mbps '+(d.eth_duplex?'Full':'Half')+'-duplex';"
"E('phy').textContent=d.eth_phy;"
"E('mac').textContent=d.eth_mac;"
"E('ip').textContent=d.eth_ip;"
"E('gw').textContent=d.eth_gw;"
"E('nm').textContent=d.eth_netmask;"
"window._wifiIp=d.wifi_got_ip?d.wifi_ip:null;"
"E('wst').textContent=d.wifi_connected?(d.wifi_got_ip?'Connected':'No IP'):'Disconnected';"
"E('wst').style.color=d.wifi_got_ip?'#4a6':(d.wifi_connected?'#ff0':'#f66');"
"E('wssid').textContent=d.wifi_ssid||'--';"
"E('wrssi').textContent=d.wifi_connected?(d.wifi_rssi+' dBm'):'--';"
"E('wch').textContent=d.wifi_connected?d.wifi_channel:'--';"
"E('wauth').textContent=d.wifi_auth||'--';"
"E('wmac').textContent=d.wifi_mac||'--';"
"E('wip').textContent=d.wifi_ip||'--';"
"E('wgw').textContent=d.wifi_gw||'--';"
"E('wnm').textContent=d.wifi_netmask||'--';"
"E('wbtn').textContent=d.wifi_connected?'Disconnect':'Connect';"
"E('wbtn').style.background=d.wifi_connected?'#3a1a1a':'#0f3460';"
"E('wbtn').style.borderColor=d.wifi_connected?'#ff6b6b':'#00d4ff';"
"E('wbtn').style.color=d.wifi_connected?'#ff6b6b':'#00d4ff';"
"E('pub').textContent=d.pub_count;"
"for(var i=0;i<4;i++){E('s'+i).textContent=Math.round(d.servos[i])+'\\u00B0';"
"if(!document.activeElement||document.activeElement.id!=='sv'+i)E('sv'+i).value=Math.round(d.servos[i])}"
"E('tc').textContent=d.task_count;"
"E('cc').textContent=d.core0_tasks+' / '+d.core1_tasks;"
"var h='';for(var i=0;i<d.tasks.length;i++){var t=d.tasks[i];"
"h+='<tr><td>'+t.name+'</td><td>'+(t.core<0?'Any':t.core)+'</td><td>'+t.pri+'</td><td>'+t.hwm+' B</td></tr>'}"
"E('tt').innerHTML=h;"
"var umm=d.ultrasonic_mm;"
"if(umm>=0){var cm=(umm/10).toFixed(1);E('udist').textContent=cm+' cm';E('umm').textContent=umm+' mm';"
"var up=Math.min(100,Math.round(umm*100/4000));E('ub').style.width=Math.max(2,up)+'%'}"
"else{E('udist').textContent='N/A';E('umm').textContent='--';E('ub').style.width='0%'}"
"updRadio(d.radio_playing,d.radio_title,d.radio_status,d.radio_source,d.radio_paused);"
"if(!document.activeElement||document.activeElement.id!=='rvol'){"
"E('rvol').value=d.radio_volume;E('rvlbl').textContent=d.radio_volume+'%'}"
"if(!document.activeElement||document.activeElement.id!=='rsrc'){"
"E('rsrc').value=d.radio_source||'sdcard'}"
"updLed(d.led_lightshow,d.led_vu);"
"updOled(d.oled_live,d.oled_vu);"
"E('ts').textContent='Updated: '+new Date().toLocaleTimeString();"
"}).catch(function(e){E('err').textContent='Connection lost'})}"
"function radioToggle(){"
"var playing=E('rbtn').textContent==='Stop';"
"fetch('/api/radio',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:playing?'stop':'play'})}).then(function(r){return r.json()}).then(function(d){"
"updRadio(d.playing,d.title,d.status)}).catch(function(){})}"
"function radioVol(v){"
"E('rvlbl').textContent=v+'%';"
"fetch('/api/radio',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({volume:parseInt(v)})}).catch(function(){})}"
"function radioCmd(a){"
"fetch('/api/radio',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:a})}).then(function(r){return r.json()}).then(function(d){"
"updRadio(d.playing,d.title,d.status,d.source,d.paused)}).catch(function(){})}"
"function radioSrc(v){"
"fetch('/api/radio',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({source:v})}).then(function(r){return r.json()}).then(function(d){"
"updRadio(d.playing,d.title,d.status,d.source,d.paused)}).catch(function(){})}"
"function updRadio(p,t,st,src,pa){"
"E('rbtn').textContent=p?'Stop':'Play';"
"E('rbtn').style.background=p?'#3a1a1a':'#0f3460';"
"E('rbtn').style.borderColor=p?'#ff6b6b':'#00d4ff';"
"E('rbtn').style.color=p?'#ff6b6b':'#00d4ff';"
"E('rstat').textContent=st||'--';"
"E('rstat').style.color=p?'#4a6':'#8899aa';"
"E('rtitle').textContent=t||'--';"
"E('rsrclbl').textContent=src==='stream'?'SLAY Radio':'SD Card';"
"E('rpause').style.background=pa?'#3a3a1a':'#0f3460';"
"E('rpause').style.borderColor=pa?'#ffcc00':'#00d4ff';"
"E('rpause').style.color=pa?'#ffcc00':'#00d4ff'}"
"var bwRunning=false;"
"function bwTest(type){"
"if(bwRunning)return;"
"bwRunning=true;"
"var btns=document.querySelectorAll('.btn');btns.forEach(function(b){b.disabled=true});"
"E('bws').textContent='Testing '+type+'...';E('bws').style.color='#ff0';"
"E('bwt').textContent='--';E('bwd').textContent='--';E('bwz').textContent='--';"
"E('bwb').style.width='0%';"
"var sz=2*1024*1024;"
"var t0=performance.now();"
"fetch('/api/bandwidth-test?type='+type+'&size='+sz).then(function(r){"
"var total=parseInt(r.headers.get('content-length'))||sz;"
"var reader=r.body.getReader();var received=0;"
"function pump(){"
"return reader.read().then(function(result){"
"if(result.done)return received;"
"received+=result.value.length;"
"var p=Math.min(100,Math.round(received*100/total));"
"E('bwb').style.width=p+'%';"
"return pump();"
"})}"
"return pump();"
"}).then(function(bytes){"
"var dt=(performance.now()-t0)/1000;"
"var mbps=(bytes*8/dt/1e6).toFixed(2);"
"E('bws').textContent='Complete';E('bws').style.color='#4a6';"
"E('bwt').textContent=mbps+' Mbps';"
"E('bwd').textContent=(dt*1000).toFixed(0)+' ms';"
"E('bwz').textContent=(bytes/1048576).toFixed(1)+' MB ('+type+')';"
"E('bwb').style.width='100%';"
"bwRunning=false;btns.forEach(function(b){b.disabled=false});"
"}).catch(function(e){"
"E('bws').textContent='Failed';E('bws').style.color='#f66';"
"bwRunning=false;btns.forEach(function(b){b.disabled=false});"
"})}"
"var wbwRunning=false;"
"function bwTestWifi(type){"
"if(wbwRunning||!window._wifiIp)return;"
"wbwRunning=true;"
"var btns=document.querySelectorAll('.btn');btns.forEach(function(b){b.disabled=true});"
"E('wbws').textContent='Testing '+type+'...';E('wbws').style.color='#ff0';"
"E('wbwt').textContent='--';E('wbwd').textContent='--';E('wbwz').textContent='--';"
"E('wbwb').style.width='0%';"
"var sz=2*1024*1024;"
"var t0=performance.now();"
"var url='http://'+window._wifiIp+':'+location.port+'/api/bandwidth-test?type='+type+'&size='+sz;"
"fetch(url).then(function(r){"
"var total=parseInt(r.headers.get('content-length'))||sz;"
"var reader=r.body.getReader();var received=0;"
"function pump(){"
"return reader.read().then(function(result){"
"if(result.done)return received;"
"received+=result.value.length;"
"var p=Math.min(100,Math.round(received*100/total));"
"E('wbwb').style.width=p+'%';"
"return pump();"
"})}"
"return pump();"
"}).then(function(bytes){"
"var dt=(performance.now()-t0)/1000;"
"var mbps=(bytes*8/dt/1e6).toFixed(2);"
"E('wbws').textContent='Complete';E('wbws').style.color='#4a6';"
"E('wbwt').textContent=mbps+' Mbps';"
"E('wbwd').textContent=(dt*1000).toFixed(0)+' ms';"
"E('wbwz').textContent=(bytes/1048576).toFixed(1)+' MB ('+type+')';"
"E('wbwb').style.width='100%';"
"wbwRunning=false;btns.forEach(function(b){b.disabled=false});"
"}).catch(function(e){"
"E('wbws').textContent='Failed: '+e.message;E('wbws').style.color='#f66';"
"wbwRunning=false;btns.forEach(function(b){b.disabled=false});"
"})}"
"function wifiToggle(){"
"var conn=E('wbtn').textContent==='Disconnect';"
"fetch('/api/wifi',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:conn?'disconnect':'connect'})}).then(function(r){return r.json()}).then(function(d){"
"E('wbtn').textContent=d.connected?'Disconnect':'Connect';"
"E('wbtn').style.background=d.connected?'#3a1a1a':'#0f3460';"
"E('wbtn').style.borderColor=d.connected?'#ff6b6b':'#00d4ff';"
"E('wbtn').style.color=d.connected?'#ff6b6b':'#00d4ff';"
"}).catch(function(){})}"
"function setServo(ch,val){"
"E('s'+ch).textContent=val+'\\u00B0';"
"fetch('/api/servo',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({channel:ch,angle:parseInt(val)})}).catch(function(){})}"
"function centreServos(){"
"for(var i=0;i<4;i++){E('sv'+i).value=90;setServo(i,90)}}"
"function ledCmd(a){"
"fetch('/api/led',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:a})}).then(function(r){return r.json()}).then(function(d){"
"updLed(d.lightshow,d.vu)}).catch(function(){})}"
"function updLed(ls,vu){"
"E('lshow').style.background=ls?'#1a3a1a':'#0f3460';"
"E('lshow').style.borderColor=ls?'#4a6':'#00d4ff';"
"E('lshow').style.color=ls?'#4a6':'#00d4ff';"
"E('lvu').style.background=vu?'#1a3a1a':'#0f3460';"
"E('lvu').style.borderColor=vu?'#4a6':'#00d4ff';"
"E('lvu').style.color=vu?'#4a6':'#00d4ff'}"
"var _oledInv=false;"
"function oledSend(lg){"
"var t=E('oledtxt').value;var lines=t.split('\\n');"
"fetch('/api/oled',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:'text',lines:lines,large:!!lg})}).catch(function(){})}"
"function oledCmd(a){"
"fetch('/api/oled',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:a})}).then(function(r){return r.json()}).then(function(d){"
"updOled(d.live_distance,d.vu_meter)}).catch(function(){})}"
"function oledLive(){"
"fetch('/api/oled',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:'live_distance'})}).then(function(r){return r.json()}).then(function(d){"
"updOled(d.live_distance,d.vu_meter)}).catch(function(){})}"
"function oledVu(){"
"fetch('/api/oled',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:'vu'})}).then(function(r){return r.json()}).then(function(d){"
"updOled(d.live_distance,d.vu_meter)}).catch(function(){})}"
"function updOled(live,vu){"
"E('olddist').style.background=live?'#1a3a1a':'#0f3460';"
"E('olddist').style.borderColor=live?'#4a6':'#00d4ff';"
"E('olddist').style.color=live?'#4a6':'#00d4ff';"
"E('oldvu').style.background=vu?'#1a3a1a':'#0f3460';"
"E('oldvu').style.borderColor=vu?'#4a6':'#00d4ff';"
"E('oldvu').style.color=vu?'#4a6':'#00d4ff'}"
"function oledInvert(){"
"_oledInv=!_oledInv;"
"fetch('/api/oled',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:'invert',value:_oledInv})}).then(function(){"
"E('oldinv').style.background=_oledInv?'#1a3a1a':'#0f3460';"
"E('oldinv').style.borderColor=_oledInv?'#4a6':'#00d4ff';"
"E('oldinv').style.color=_oledInv?'#4a6':'#00d4ff'}).catch(function(){})}"
"function oledContrast(v){"
"fetch('/api/oled',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({action:'contrast',value:parseInt(v)})}).catch(function(){})}"
"poll();setInterval(poll,3000);"
"</script></body></html>";

#endif // DASHBOARD_H
